### ISSUE TITLE
Stale values from network tables when restarting robot code.

### ISSUE THREAD

**Issue by Kython89** [wpilibsuite/SmartDashboard#98] opened 2018-02-03 00:59 UTC
See the screen shot below.  Observe the `kpPos`

Immediately following a restart of robot code the value is stale on the SmartDashboard.  In the outline viewer it correctly shows `kpPos` as `0`.

If you use `SmartDashboard::GetNumber("kpPos", 0);` it will return 0 instead of 4.  If you change the 4.0 to a 5.0 and then use `SmartDashboard::GetNumber("kpPos", 0);` it returns the correct value of 5.0.

It is very misleading and hard to debug when debugging tools aren't updating properly.

![smartdashboard](https://user-images.githubusercontent.com/13496307/35761167-4a0d3cd4-084b-11e8-9280-d5d98c34bee6.png)

**Comment by virtuald** [comment] 2018-03-01 18:39
I'd be willing to bet that this is caused by https://github.com/wpilibsuite/ntcore/pull/270

**Comment by AustinShalit** [comment] 2020-10-28 01:54
Closed by wpilibsuite/ntcore#270

**Closed by AustinShalit** 2020-10-28 01:54 UTC
